import { setThemeConfig } from '@repo/ui/system/createThemeConfig';
import type { Metadata } from 'next';

import { appTheme } from './theme.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// console.log(appTheme);

setThemeConfig({
  theme: appTheme,
  sprinkles,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>{children}</body>
    </html>
  );
}
