import type { Colors } from './color.type';
export const color: Colors = {
  variant: {
    primary: {
      solidColor: 'primary.50',
      solidActiveColor: 'primary.100',
      solidBg: 'primary.500',
      solidHoverBg: 'primary.100',
      solidActiveBg: 'primary.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'primary.50',
      softActiveColor: 'primary.100',
      softBg: 'primary.50',
      softHoverBg: 'primary.100',
      softActiveBg: 'primary.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'primary.500',
      outlineActiveColor: 'primary.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'primary.100',
      outlineActiveBg: 'primary.200',
      outlineBorder: 'primary.500',
      outlineHoverBorder: 'primary.600',
      outlineActiveBorder: 'primary.700',

      ghostColor: 'primary.500',
      ghostActiveColor: 'primary.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    secondary: {
      solidColor: 'secondary.50',
      solidActiveColor: 'secondary.100',
      solidBg: 'secondary.50',
      solidHoverBg: 'secondary.100',
      solidActiveBg: 'secondary.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'secondary.50',
      softActiveColor: 'secondary.100',
      softBg: 'secondary.50',
      softHoverBg: 'secondary.100',
      softActiveBg: 'secondary.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'secondary.500',
      outlineActiveColor: 'secondary.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'secondary.100',
      outlineActiveBg: 'secondary.200',
      outlineBorder: 'secondary.500',
      outlineHoverBorder: 'secondary.600',
      outlineActiveBorder: 'secondary.700',

      ghostColor: 'secondary.500',
      ghostActiveColor: 'secondary.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    tertiary: {
      solidColor: 'tertiary.50',
      solidActiveColor: 'tertiary.100',
      solidBg: 'tertiary.50',
      solidHoverBg: 'tertiary.100',
      solidActiveBg: 'tertiary.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'tertiary.50',
      softActiveColor: 'tertiary.100',
      softBg: 'tertiary.50',
      softHoverBg: 'tertiary.100',
      softActiveBg: 'tertiary.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'tertiary.500',
      outlineActiveColor: 'tertiary.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'tertiary.100',
      outlineActiveBg: 'tertiary.200',
      outlineBorder: 'tertiary.500',
      outlineHoverBorder: 'tertiary.600',
      outlineActiveBorder: 'tertiary.700',

      ghostColor: 'tertiary.500',
      ghostActiveColor: 'tertiary.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    info: {
      solidColor: 'info.50',
      solidActiveColor: 'info.100',
      solidBg: 'info.50',
      solidHoverBg: 'info.100',
      solidActiveBg: 'info.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'info.50',
      softActiveColor: 'info.100',
      softBg: 'info.50',
      softHoverBg: 'info.100',
      softActiveBg: 'info.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'info.500',
      outlineActiveColor: 'info.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'info.100',
      outlineActiveBg: 'info.200',
      outlineBorder: 'info.500',
      outlineHoverBorder: 'info.600',
      outlineActiveBorder: 'info.700',

      ghostColor: 'info.500',
      ghostActiveColor: 'info.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    error: {
      solidColor: 'error.50',
      solidActiveColor: 'error.100',
      solidBg: 'error.50',
      solidHoverBg: 'error.100',
      solidActiveBg: 'error.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'error.50',
      softActiveColor: 'error.100',
      softBg: 'error.50',
      softHoverBg: 'error.100',
      softActiveBg: 'error.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'error.500',
      outlineActiveColor: 'error.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'error.100',
      outlineActiveBg: 'error.200',
      outlineBorder: 'error.500',
      outlineHoverBorder: 'error.600',
      outlineActiveBorder: 'error.700',

      ghostColor: 'error.500',
      ghostActiveColor: 'error.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    success: {
      solidColor: 'success.50',
      solidActiveColor: 'success.100',
      solidBg: 'success.50',
      solidHoverBg: 'success.100',
      solidActiveBg: 'success.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'success.50',
      softActiveColor: 'success.100',
      softBg: 'success.50',
      softHoverBg: 'success.100',
      softActiveBg: 'success.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'success.500',
      outlineActiveColor: 'success.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'success.100',
      outlineActiveBg: 'success.200',
      outlineBorder: 'success.500',
      outlineHoverBorder: 'success.600',
      outlineActiveBorder: 'success.700',

      ghostColor: 'success.500',
      ghostActiveColor: 'success.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    warning: {
      solidColor: 'warning.50',
      solidActiveColor: 'warning.100',
      solidBg: 'warning.50',
      solidHoverBg: 'warning.100',
      solidActiveBg: 'warning.200',
      solidBorder: 'transparent',
      solidHoverBorder: 'transparent',
      solidActiveBorder: 'transparent',

      softColor: 'warning.50',
      softActiveColor: 'warning.100',
      softBg: 'warning.50',
      softHoverBg: 'warning.100',
      softActiveBg: 'warning.200',
      softBorder: 'transparent',
      softHoverBorder: 'transparent',
      softActiveBorder: 'transparent',

      outlineColor: 'warning.500',
      outlineActiveColor: 'warning.600',
      outlineBg: 'transparent',
      outlineHoverBg: 'warning.100',
      outlineActiveBg: 'warning.200',
      outlineBorder: 'warning.500',
      outlineHoverBorder: 'warning.600',
      outlineActiveBorder: 'warning.700',

      ghostColor: 'warning.500',
      ghostActiveColor: 'warning.600',
      ghostBorder: 'transparent',
      ghostHoverBorder: 'transparent',
      ghostActiveBorder: 'transparent',
      ghostBg: 'transparent',
      ghostHoverBg: 'transparent',
      ghostActiveBg: 'transparent',
    },
    disabled: {
      solidColor: 'gray.400',
      solidBg: 'gray.300',
      solidBorder: 'transparent',

      softColor: 'gray.400',
      softBg: 'gray.100',
      softBorder: 'transparent',

      outlineColor: 'gray.400',
      outlineBg: 'transparent',
      outlineBorder: 'gray.400',

      ghostColor: 'gray.400',
      ghostBg: 'transparent',
      ghostBorder: 'transparent',
    },
  },
  content: {
    primary: 'gray.900',
    secondary: 'gray.700',
    tertiary: 'gray.500',
    info: 'info.500',
    error: 'error.500',
    success: 'success.500',
    warning: 'warning.500',
  },
  bg: {
    primary: 'common.white',
    secondary: 'gray.50',
    tertiary: 'gray.100',
    info: 'info.100',
    error: 'error.100',
    success: 'success.100',
    warning: 'warning.100',
  },
  surface: {
    none: 'none',
    low: '0 1px 3px rgba(0,0,0,0.12)',
    medium: '0 4px 6px rgba(0,0,0,0.15)',
    raised: '0 6px 12px rgba(0,0,0,0.18)',
    high: '0 12px 24px rgba(0,0,0,0.22)',
    highest: '0 24px 38px rgba(0,0,0,0.25)',
  },
  overlay: {
    none: 'rgba(0, 0, 0, 0)',
    low: 'rgba(0, 0, 0, 0.15)',
    medium: 'rgba(0, 0, 0, 0.3)',
    raised: 'rgba(0, 0, 0, 0.5)',
    high: 'rgba(0, 0, 0, 0.7)',
    highest: 'rgba(0, 0, 0, 0.9)',
  },
};
